module.exports = {
  "The Arts": [
    "Painting",
    "Sculpture",
    "Architecture",
    "Dance",
    "Literature",
    "Opera",
    "Stand-up",
    "Comic Books",
    "Illustration",
    "Music",
    "Theatre",
    "Cinema",
    "Video Games",
    "Graffiti",
    "Fashion",
    "Photography"
  ],
  "Bands": [
    "The Beatles",
    "The Rolling Stones",
    "Fleetwood Mac",
    "Nirvana",
    "Take That",
    "Blondie",
    "Spice Girls",
    "Queen",
    "The Beach Boys",
    "Madonna",
    "Destiny's Child",
    "Jackson 5",
    "ABBA",
    "Little Mix",
    "The White Stripes",
    "U2"
  ],
  "Cities": [
    "New York City",
    "Moscow",
    "Dehli",
    "London",
    "Paris",
    "Rome",
    "Rio de Janeiro",
    "Sydney",
    "Tokyo",
    "Athens",
    "Cairo",
    "Hong Kong",
    "Chicago",
    "Los Angeles",
    "San Francisco",
    "Jerusalem"
  ],
  "Civilizations": [
    "Romans",
    "Egyptians",
    "Mayans",
    "Mongols",
    "Aztecs",
    "Japanese",
    "Persians",
    "Greeks",
    "Turks",
    "Vikings",
    "Incas",
    "Spanish",
    "Zulu",
    "Chinese",
    "Spartans",
    "Aliens"
  ],
  "Countries": [
    "UK",
    "Spain",
    "Japan",
    "Brazil",
    "France",
    "USA",
    "Italy",
    "Australia",
    "Germany",
    "Mexico",
    "India",
    "Israel",
    "Canada",
    "China",
    "Russia",
    "Egypt"
  ],
  "Fairy Tales": [
    "Cinderella",
    "Goldilocks",
    "Jack and the Beanstalk",
    "Hare and the Tortoise",
    "Snow White",
    "Rapunzel",
    "Aladdin",
    "Princess and the Pea",
    "Peter Pan",
    "Little Red Riding Hood",
    "Pinocchio",
    "Beauty and the Beast",
    "Sleeping Beauty",
    "Hansel and Gretel",
    "Gingerbred Man",
    "Three Little Pigs"
  ],
  "Food": [
    "Pizza",
    "Pasta",
    "Eggs",
    "Sausage",
    "Potatoes",
    "Salad",
    "Cheese",
    "Ice Cream",
    "Fish",
    "Soup",
    "Fruit",
    "Chocolate",
    "Cake",
    "Bread",
    "Chicken",
    "Beef"
  ],
  "Hobbies": [
    "Stamps",
    "Trains",
    "Model Making",
    "Knitting",
    "Fishing",
    "Reading",
    "Painting",
    "Gardening",
    "Sailing",
    "Travel",
    "Walking",
    "Pottery",
    "Cooking",
    "Yoga",
    "Photography",
    "Hiking"
  ],
  "Inventions": [
    "Matches",
    "Gunpowder",
    "Wheel",
    "Printing",
    "Computer",
    "Internet",
    "Compass",
    "Plane",
    "TV",
    "Electricity",
    "Writing",
    "Steam Engine",
    "Car",
    "Telephone",
    "Camera",
    "Radio"
  ],
  "Movies": [
    "Jurassic Park",
    "Jaws",
    "Raiders of the Lost Ark",
    "The Avengers",
    "Transformers",
    "Toy Story",
    "Home Alone",
    "Titanic",
    "E.T.",
    "The Wizard of Oz",
    "King Kong",
    "The Matrix",
    "Shrek",
    "The Godfather",
    "Finding Nemo",
    "Avatar"
  ],
  "Musicals": [
    "West Side Story",
    "Cats",
    "Jersey Boys",
    "School of Rock",
    "Phantom of the Opera",
    "Les Miserables",
    "Oliver",
    "Hamilton",
    "Chicago",
    "42nd Street",
    "Annie",
    "Book of Mormon",
    "Lion King",
    "Wicked",
    "Hairspray",
    "Mamma Mia"
  ],
  "Musical Instruments": [
    "Electric Guitar",
    "Piano",
    "Violin",
    "Drums",
    "Bass Guitar",
    "Saxophone",
    "Cello",
    "Flute",
    "Clarinet",
    "Trumpet",
    "Voice",
    "Ukulele",
    "Harp",
    "Bagpipes",
    "Harmonica",
    "Banjo"
  ],
  "Mythical Creatures": [
    "Cyclops",
    "Pegasus",
    "Medusa",
    "Sphinx",
    "Werewolf",
    "Unicorn",
    "Dragon",
    "Troll",
    "Loch Ness Monster",
    "Mermaid",
    "Phoenix",
    "Vampire",
    "Minotaur",
    "Hydra",
    "Yeti",
    "Centaur"
  ],
  "School": [
    "Maths",
    "Chemistry",
    "Physics",
    "Biology",
    "History",
    "Philosophy",
    "Geography",
    "English",
    "Economics",
    "French",
    "Art",
    "Music",
    "P.E.",
    "Latin",
    "Religion",
    "Technology"
  ],
  "Rooms": [
    "Kitchen",
    "Hallway",
    "Greenhouse",
    "Bedroom",
    "Bathroom",
    "Dining Room",
    "Office",
    "Living Room",
    "Attic",
    "Basement",
    "Dungeon",
    "Nursery",
    "Pantry",
    "Bunker",
    "Shed",
    "Garage"
  ],
  "Sports": [
    "Football",
    "Cricket",
    "Golf",
    "Snooker",
    "Basketball",
    "Rugby",
    "Sailing",
    "Squash",
    "Tennis",
    "Badminton",
    "Motor Racing",
    "Wrestling",
    "Lacrosse",
    "Volleyball",
    "Triathlon",
    "Cycling"
  ],
  "Tattoos": [
    "Stars",
    "Angel",
    "Wings",
    "Dragon",
    "Eagle",
    "Fairy",
    "Heart",
    "Skull",
    "Sword",
    "Tiger",
    "Swallows",
    "Flower",
    "Butterfly",
    "Cross",
    "Owl",
    "Anchor"
  ],
  "Toys": [
    "Lego",
    "Rocking Horse",
    "Super Soaker",
    "Beanie Babies",
    "Rubik's Cube",
    "Etch a Sketch",
    "Teddy Bear",
    "Play Doh",
    "Yo-yo",
    "Frisbee",
    "Hot Wheels",
    "Barbie",
    "Slinky",
    "Action Man",
    "Hula Hoop",
    "Swingball"
  ],
  "Transport": [
    "Plane",
    "Car",
    "Tank",
    "Helicopter",
    "Cruise Ship",
    "Hovercraft",
    "Motorbike",
    "Bus",
    "Segway",
    "Cable Car",
    "Jet Ski",
    "Hot Air Balloon",
    "Train",
    "Spaceship",
    "Magic Carpet",
    "Broomstick"
  ],
  "Zoo": [
    "Elephant",
    "Giraffe",
    "Koala",
    "Tiger",
    "Lion",
    "Leopard",
    "Meerkat",
    "Buffalo",
    "Ostrich",
    "Owl",
    "Eagle",
    "Parrot",
    "Scorpion",
    "Alligator",
    "Zebra",
    "Gorilla"
  ]
}